language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
  # - rbx
services:
  - mongodb
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.4.2/bin/elasticsearch" rake elasticsearch:start
  - appraisal install
script:
  - appraisal rake
