language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  # - rbx
env:
  - PAGINATOR=kaminari
  - PAGINATOR=will_paginate
  - PAGINATOR=
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.0.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.3.0/bin/elasticsearch" rake elasticsearch:start
